version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: bundle install

      - run:
          name: Greeting
          command: echo Welcome BrewMaster!
          
      - run:
          name: Print the Current Time
          command: date
       
       - run:
          name: build the jekyll site
          command: bundle exec jekyll build
